return {
	["CELL_SIZE"] = 24,
	["STREAMING_PADDING"] = 50,
	["DELOAD_DELAY"] = 3,
	["POSITION_CHECK_INTERVAL"] = 0.1,
	["POSITION_THRESHOLD"] = 2,
	["LOAD_WAVE_STAGGER"] = 0.1,
	["DELOAD_WAVE_STAGGER"] = 0.1,
	["LOAD_PLANTS_PER_FRAME"] = 6,
	["DELOAD_PLANTS_PER_FRAME"] = 10
}