--!nocheck
local Constants = {}

Constants.Version = "2569.03.12-21.08"
Constants.Pos = {
	GearShop = CFrame.new(211.64, 205.47, 608.18),
	SeedShop = CFrame.new(176.70, 205.49, 672.00),
	Botanist = CFrame.new(214.00, 205.47, 621.05),
	Sell = CFrame.new(149.40, 205.51, 672.00),
	Quest = CFrame.new(111.52, 205.50, 635.02),
}

Constants.SutaDistLimit = 14
Constants.SutaYoffset = 4
Constants.PlantsESPFolderName = "PlantsESP"
Constants.FruitESPFolderName = "FruitESP"

return Constants
