name: Build and Release EfHub

on:
  release:
    types: [published]

# --- เพิ่ม 2 บรรทัดนี้เข้าไป เพื่ออนุญาตให้บอทอัปโหลดไฟล์ได้ ---
permissions:
  contents: write
# --------------------------------------------------------

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Darklua
        run: |
          wget https://github.com/seaofvoices/darklua/releases/latest/download/darklua-linux-x86_64.zip
          unzip darklua-linux-x86_64.zip
          chmod +x darklua
          sudo mv darklua /usr/local/bin/

      - name: Auto Switch to Release Mode
        run: |
          sed -i 's/getgenv().DEV_MODE = true/getgenv().DEV_MODE = false/g' src/loader.luau

      - name: Bundle Code with Darklua
        run: darklua process src/loader.luau EfHub_Release.lua

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          files: EfHub_Release.lua
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}